[project]
name = "ktts-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kokoro>=0.9.4",
    "numpy>=2.2.6",
    "pip>=25.1.1",
    "soundfile>=0.13.1",
]

[project.scripts]
ktts-cli = "main:main"
